<?php

namespace JSDataTables\Filter;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-15 at 04:53:04.
 */
class ColumnFilterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ColumnFilter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        /* [
          'nome' => [
          'db' => [
          'alias' => 'b'
          ],
          'dt' => [
          'width' => '20%',
          'orderable' => false,
          'searchable' => true,
          ]
          ]
          ]; */
        $this->object = new ColumnFilter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    public function dataInvalidProvider() {
        return array(
            array('data', array(null)),
            array('name', array(null)),
            array('searchable', array(null)),
            array('orderable', array(null)),
        );
    }

    /**
     * @dataProvider dataInvalidProvider
     */
    public function testIfIsInvalid($input, $values) {
        foreach ($values as $value) {
            $this->object->get($input)->setValue($value);
            $this->assertFalse($this->object->get($input)->isValid());
        }
    }

    public function testIfIsValid() {
        $valid1 = [
            'data' => 'data_teste',
            'name' => '',
            'searchable' => 'true',
            'orderable' => 'true',
            'search' => [
                'value' => 'value teste',
                'regex' => 'false'
            ]
        ];
        $this->object->setData($valid1);
        $this->assertTrue($this->object->isValid());
    }

}
