<?php

namespace Veiculo\DataTables;

use JS\Test\JSTestControllerCase;
use Veiculo\Entity\Veiculo;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-25 at 01:52:38.
 */
class VeiculoDataTablesTest extends JSTestControllerCase {

    /**
     * @var VeiculoDataTables
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        parent::setUp();
        $this->getRequest()->getQuery()->fromArray([
            'draw' => '1',
            'start' => '0',
            'length' => '125',
            'search' => [
                'value' => 'HIR3333',
                'regex' => 'false'
            ],
            'columns' => [
                [
                    'data' => 'codigo',
                    'name' => '',
                    'searchable' => 'false',
                    'orderable' => 'false',
                    'search' => [
                        'value' => '',
                        'regex' => 'false'
                    ]
                ],
                [
                    'data' => 'placa',
                    'name' => '',
                    'searchable' => 'true',
                    'orderable' => 'true',
                    'search' => [
                        'value' => '',
                        'regex' => 'false'
                    ]
                ],
                [
                    'data' => 'descricao',
                    'name' => '',
                    'searchable' => 'true',
                    'orderable' => 'true',
                    'search' => [
                        'value' => '',
                        'regex' => 'false'
                    ]
                ]
            ],
            /* 'order' => [
                  [
                  'column' => '1',
                  'dir' => 'asc'
                  ]
                  ] */
        ]);
        $this->object = $this->getServiceManager()->get('DataTablesManager')->getDt('Veiculo\Entity\Veiculo');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        parent::tearDown();
    }

    public function testGetData() {
        $veiculoPadrao = new Veiculo();
        $veiculoPadrao->setDescricao('Veiculo Padrão');
        $veiculoPadrao->setPlaca('HIR0000');

        $veiculo1 = new Veiculo();
        $veiculo1->setDescricao('Veiculo 1');
        $veiculo1->setPlaca('HIR1111');
        $veiculo1->setKmInicio(100);

        $veiculo2 = new Veiculo();
        $veiculo2->setDescricao('Veiculo 2');
        $veiculo2->setPlaca('HIR2222');
        $veiculo2->setKmInicio(200);

        $veiculo3 = new Veiculo();
        $veiculo3->setDescricao('Veiculo 3');
        $veiculo3->setPlaca('HIR3333');
        $veiculo3->setKmInicio(300);

        $this->getEntityManager()->persist($veiculoPadrao);
        $this->getEntityManager()->persist($veiculo1);
        $this->getEntityManager()->persist($veiculo2);
        $this->getEntityManager()->persist($veiculo3);
        $this->getEntityManager()->flush();
        $a = $this->object->getData();
    }

}
