<?php

namespace JSDataTables\Doctrine\ORM\Query\Expr;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-23 at 22:33:14.
 */
class OrderByTest extends \PHPUnit_Framework_TestCase {

    private $ajaxParams = [
        'draw' => '1',
        'start' => '0',
        'length' => '125',
        'search' => [
            'value' => 'value teste global',
            'regex' => 'false'
        ],
        'columns' => [
            [
                'data' => 'data_teste1',
                'name' => '',
                'searchable' => 'true',
                'orderable' => 'true',
                'search' => [
                    'value' => 'value teste1',
                    'regex' => 'false'
                ]
            ],
            [
                'data' => 'data_teste2',
                'name' => '',
                'searchable' => 'true',
                'orderable' => 'true',
                'search' => [
                    'value' => 'value teste2',
                    'regex' => 'false'
                ]
            ]
        ],
        'order' => [
            [
                'column' => '1',
                'dir' => 'asc'
            ]
        ]
    ];
    private $dtConfig = [
        'columns' => [
            [
                'data' => 'data_teste1',
                'name' => 'data teste 1',
                'width' => '20%',
                'orderable' => true,
                'searchable' => true,
                'server' => [
                    'field' => [
                        'name' => 'data_teste1',
                        'alias' => 'a'
                    ],
                    'filters' => [
                        [
                            'name' => '',
                            'options' => ''
                        ]
                    ],
                    'separator' => '~',
                ]
            ],
            [
                'data' => 'data_teste2',
                'name' => 'data teste 2',
                'width' => '20%',
                'orderable' => true,
                'searchable' => true,
                'server' => [
                    'field' => [
                        'name' => 'data_teste1',
                        'alias' => 'a',
                        'partial' => true
                    ],
                    'filters' => [
                        [
                            'name' => '',
                            'options' => ''
                        ]
                    ],
                    'separator' => '~',
                ]
            ],
        ],
    ];

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {

    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {

    }

    /**
     * @covers JSDataTables\Doctrine\ORM\Query\Expr\OrderBy::generateOrderBy
     */
    public function testGenerateOrderBy() {
        $order = new OrderBy();
        $ajaxParams = new \JSDataTables\Entity\AjaxParams();
        $dtConfig = new \JSDataTables\Entity\ConfigDt();
        $dtConfig = $dtConfig->hydrate($this->dtConfig);
        echo $order->generateOrderBy($dtConfig, $ajaxParams->hydrate($this->ajaxParams));
    }

}
