<?php

namespace JSDataTables\Service;

use JS\Test\JSTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-04-24 at 18:40:20.
 */
class FieldFilterManagerTest extends JSTestCase {

    /**
     * @var FieldFilterManager
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        parent::setUp();
        $this->object = $this->getServiceManager()->get('FieldFilterManager');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        parent::tearDown();
    }

    /**
     * @covers JSDataTables\Service\FieldFilterManager::filter
     */
    public function testFilter() {
        $filters = [
            [
                'name' => 'StringTrim'
            ],
            [
                'name' => 'StringToUpper',
                'options' => [
                    'encoding' => 'UTF-8'
                ]
            ]
        ];
        $this->assertEquals($this->object->filter($filters, ' luiz carlos '), 'LUIZ CARLOS');
    }

}
